# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45691e8d76a4ceb6a6f42f50eabeaef8d1dab8ce197ce4ba12e9db8ab1ad30be06c179506d83efb73efd4c6c85e80054ddd5a95334b9ebf8e3dba8fd2cbf9f00

test:
  secret_key_base: fc20ea21ff6fb1f7f8037081f9d264165f5ed27da7f3726a6d306f6978c6c74d0dccc1da9ad0a1cf28f2a631bbe48fdde0a8ab4220b1d32882719062b6d6085a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
